"""State en las visitas

Revision ID: 010027cb017f
Revises: 385c03ce3fd7
Create Date: 2026-01-31 11:59:36.471197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010027cb017f'
down_revision: Union[str, Sequence[str], None] = '385c03ce3fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MedicineVisit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('State', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('State', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Visit', schema=None) as batch_op:
        batch_op.drop_column('State')

    with op.batch_alter_table('MedicineVisit', schema=None) as batch_op:
        batch_op.drop_column('State')

    # ### end Alembic commands ###
