"""Desarrollo de las relaciones

Revision ID: 54f15752606d
Revises: 402eada7146c
Create Date: 2026-01-26 12:01:37.487576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f15752606d'
down_revision: Union[str, Sequence[str], None] = '402eada7146c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SpecialtyId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_doctor_specialty_id', 'Specialty', ['SpecialtyId'], ['Id'])
        batch_op.drop_column('Specialty')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Specialty', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_doctor_specialty_id', type_='foreignkey')
        batch_op.drop_column('SpecialtyId')

    # ### end Alembic commands ###
